Add Ukrainian; bump version
cospired/i18n-iso-languages pull request #43
Opened 2022-03-12 10:58 UTC by serhiipalash

2022-03-14 21:30 UTC, serhiipalash commented
ping @e110c0

2022-03-16 14:55 UTC, e110c0 requested changes

2022-03-16 14:55 UTC, e110c0 commented on CHANGELOG.md
> +# 3.1.2
please either change this to 'unreleased' since version might be different

2022-03-16 14:55 UTC, e110c0 commented on entry-node.js
> +const uk = require('./langs/uk.json');
chore: please add this in alphabetical order

2022-03-17 12:19 UTC, serhiipalash commented
@e110c0 I've fixed all issues you mentioned.

2022-03-17 20:14 UTC, e110c0 approved these changes

2022-03-17 20:15 UTC, merged